=== ThanhDang1008/XML-VoThanhDang/buoi_3 dtd/student_ID.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="school">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="date" type="xs:date"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="class" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="ref" type="xs:IDREF" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ThanhDang1008/XML-VoThanhDang/buoi_3 dtd/student_ID.xml
<?xml version="1.0" encoding="UTF-8"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="student_ID.xsd">
    <student id="SV01">
        <name>Nguyễn Thị Thanh Thủy</name>
        <date>1997-12-20</date>
    </student>
    <student id="SV02">
        <name>Lê Thị Hồng Cẩm</name>
        <date>1998-1-21</date>
    </student>
    <class ref="SV01">Class A</class>
    <class ref="SV02">Class A</class>
</school>
